### ISSUE TITLE
YAML Based Config

### ISSUE THREAD

**Issue by krak3n** [krak3n/Facio#18]
The ini style config style format is a tad limiting. A YAML based one will give greater flexibility in configurable options and be much clearer.

**Comment by krak3n** [comment]
Example:

```
templates:
  - my_templae: git+git@github.com:/my/repo.git
  - experimenta: /local/path/to/template
python:
  - create_virtualenv: True
  - virtualenv_root: /home/vagrant/.virtualenvs
  - install_as_egg: False
```

This is quite a substantial overhaul of the configuration system.
